name: Build and publish a Docker mage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21.4
      - name: instal node
        run: sudo apt install nodejs -y
        
      - run: npm install -g pnpm
      #- run: export SHELL=/usr/bin/bash
      #- run: sudo wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" sh -
      #- run: source /home/runner/.shrc
      - run: pnpm --version
      - run: pnpm version
        
      - name: Source AUTHELIA
        run: source bootstrap.sh
        
      - name: Build AUTHELIA
        run: authelia-scripts docker build
