name: Build and publish a Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21.4
      - run: sudo apt update
      
      - name: install node
        run: sudo apt install nodejs -y
        
      - run: npm install -g pnpm
        
      - name: Source AUTHELIA
        run: |
          source bootstrap.sh 
          git tag latest
          authelia-scripts docker build
          docker tag authelia/authelia:latest cajuteq/authelia:latest
        env:
          GOPATH: /home/runner/go

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: cajuteq
          password: dckr_pat_u5GSdLs5xpdeo_xVqEOvwXVGuug
      - run: docker push cajuteq/authelia
          